export const highlightedGoals = [
  "newPost - completed",
  "newPost - started",
  "pointHelpful - completed",
  "endorse_down - completed",
  "endorse_up - completed",
  "Login and Signup - Signup Fail",
  "Login and Signup - Signup/Login Opened",
  "newPointFor - completed",
  "newPointAgainst - completed",
  "Login and Signup - Login Success",
  "Login and Signup - Signup Success",
  "pages - open",
  "pointNotHelpful - completed",
  "startTranslation - click",
  "video - completed",
  "audio - completed",
  "videoUpload - complete",
  "audioUpload - complete",
  "imageUpload - complete",
  "mediaUpload - error",
  "twitter - pointShareOpen",
  "point.report - open",
  "email - pointShareOpen",
  "post.report - open",
  "whatsapp - pointShareOpen",
  "twitter - postShareCardOpen",
  "facebook - postShareCardOpen",
  "email - postShareCardOpen",
  "whatsapp - postShareCardOpen",
  "filter - click",
  "search - click",
  "marker - clicked",
  "newUserImage",
  "filter - change",
  "newPost - open",
  "post.ratings - completed",
  "post.ratings.dialog - open",
  "recommendations - goForward",
  "recommendations - goBack",
  "setEmail - cancel",
  "setEmail - logout",
  "forgotPasswordFromSetEmail - open",
  "linkAccountsAjax - confirm",
  "setEmail - confirm",
  "registrationAnswers - submit",
  "evaluated - point toxicity low",
  "evaluated - point toxicity medium",
  "evaluated - point toxicity high",
  "evaluated - post toxicity low",
  "evaluated - post toxicity medium",
  "evaluated - post toxicity high",
  "open - share dialog options",
  "open - share dialog - brand:whatsapp",
  "open - share dialog - brand:facebook",
  "open - share dialog - brand:twitter",
  "open - share dialog - clipboard"
];