module Const
  ABOUT_QUESTION_ID = 2
  TOUR_DEMO_QUESTION_ID = 9
  RANK_ALGO_ID = 3
  VISIT_STALE_AFTER = 10800 # 3 hours
  HASH_IP = false
  MAX_QUESTION_LENGTH = 100
  MAX_ITEM_LENGTH = 140
  ITEM_LIMIT = 10
end